#! /usr/local/bin/python
# -*- mode: Python; -*-

# A simple authentication and authorization database management tool
# to support Korp configuration with CLARIN access classes; to go with
# an auth.cgi in backend/korp/. Python 2.7 (because it's what the Korp
# frontend is). By Jussi Piitulainen, jpiitula@ling.helsinki.fi, for
# FIN-CLARIN, December 2013.

from __future__ import print_function

import MySQLdb
import sys, codecs, re

DBUSER = 'ling'
DBPASS = 'PASSWORD_PLACEHOLDER'
DBNAME = 'korp_auth'

# For testing whether there is a compatible limited_access setting
# (and no incompatible limited_access settings) in the frontend.
CONFIG = { '/var/www/html/config.js',
           '/var/www/html/modes/parallel_mode.js',
}

def usage_command(cursor, command, args):
    print('''\
Usage: ./auth command [arg [arg]]

PERSON is the login identifier in HTTP Basic Authentication
CORPUS is the Corpus Workbench Name of a corpus in Korp

./auth PUB CORPUS            make corpus PUB
./auth ACA CORPUS            make corpus ACA
./auth RES CORPUS            make corpus RES
Note: ACA and RES corpora need also be configured limited_access=true,
and PUB corpora, not (that's an attribute specification in config.js
of Korp front end)

./auth lbr_register URN@LBR CORPUS     map LBR-ID to KORP-ID
./auth lbr_unregister URN@LBR CORPUS   unmap LBR-ID and KORP-ID
./auth lbr_map                         show mappings

./auth persons               list persons
./auth corpora               list corpora and their licenses

DEPRECATED, DO NOT USE:
./auth remove PERSON         remove person (idempotent)

./auth allow PERSON CORPUS   give person personal access to corpus
./auth deny PERSON CORPUS    take away from person personal access to corpus


    ''')

def remove_command(cursor, command, args):
    '''Remove person'''
    person, = args
    cursor.execute('''
    delete from auth_academic where person = %s''', [person])
    cursor.execute('''
    delete from auth_allow where person = %s''', [person])
    cursor.execute('''
    delete from auth_secret where person = %s''', [person])

def allow_command(cursor, command, args):
    '''Give person personal access to corpus'''
    person, corpus = args
    cursor.execute('''
    insert into auth_allow(person, corpus)
    values (%s, %s)
    on duplicate key
    update corpus = corpus''', [person, corpus])

def deny_command(cursor, command, args):
    '''Take away personal access to corpus from person'''
    person, corpus = args
    cursor.execute('''
    delete from auth_allow
    where person = %s and corpus = %s''', [person, corpus])

def lbr_register_command(cursor,command,args):
    '''Map a LBR URN ID to one or more (sub)coropra'''
    lbr_id, corpus = args
    cursor.execute('''
    insert into auth_lbr_map(lbr_id, corpus)
    values (%s, %s)
    on duplicate key
    update corpus = corpus''', [lbr_id, corpus])

def lbr_unregister_command(cursoer,command,args):
    '''Map a LBR URN ID to one or more (sub)coropra'''
    lbr_id, corpus = args
    cursor.execute('''
    delete from auth_lbr_map
    where lbr_id = %s and corpus = %s''', [lbr_id, corpus])

def license_command(cursor, command, args):
    '''Make corpus be of given type (PUB, ACA, or RES)'''
    license = command
    corpus, = args
    cursor.execute('''
    insert into auth_license(corpus, license)
    values (%s, %s)
    on duplicate key
    update license = %s''', [corpus, license, license])
    check_config(corpus, license)

def persons_command(cursor, command, args):
    '''List persons and their personally allowed corpora'''
    cursor.execute('''
    (select distinct person from auth_allow)
        order by person''')
    for person, in cursor.fetchall():
        print(person, end='')
        cursor.execute('''
        select corpus from auth_allow
        where person = %s
        order by corpus''', [person])
        for corpus in cursor: print(' ', corpus[0], end='')
        print()

def corpora_command(cursor, command, args):
    '''List corpora, their license (PUB, ACA, or RES), and their corporal
    persons (persons allowed personal access to the corpus)'''
    cursor.execute('''
    select corpus, license from auth_license
    order by corpus''')
    for corpus, license in cursor.fetchall():
        print(corpus, license, end='')
        cursor.execute('''
        select person from auth_allow
        where corpus = %s
        order by person''', [corpus])
        for person, in cursor:
            print('', person, end='')
        print()
        check_config(corpus, license)

def lbr_map_command(cursor, command, args):
    '''List URN@LBR-IDs and Korp-ID mappings'''
    cursor.execute('''
    select lbr_id, corpus from auth_lbr_map
    order by lbr_id''')
    for lbr_id, corpus in cursor.fetchall():
        print ("%s\t%s" % (lbr_id, corpus))

dispatch = dict(remove = remove_command,
                allow = allow_command,
                deny = deny_command,
                PUB = license_command,
                ACA = license_command,
                RES = license_command,
                persons = persons_command,
                corpora = corpora_command,
                lbr_register = lbr_register_command,
                lbr_unregister = lbr_unregister_command,
                lbr_map = lbr_map_command,
                help = usage_command)

def check_config(corpus, license):
    '''Reports on possible incompatibilities with frontend config files.
    Note! This does not cover all possibilities - if something is not
    found, the problems may well be in this function instead of in the
    config files.'''

    found_containing = []
    for config in CONFIG:
        text = codecs.open(config, 'r', 'utf-8').read()
        matches = re.findall(r'\bsettings.corpora.%s\s*=\s*[{].*?[{}]'
                             % corpus.lower(),
                             text, flags = re.MULTILINE | re.DOTALL)
        if len(matches) > 0:
            found_containing.append(config)

        if len(matches) > 1:
            print('! %s: found many in %s' % (corpus, config))

        for match in matches:
            limitations = re.findall(r'\blimited_access\s*:\s*(\w+)',
                                     match, re.MULTILINE | re.DOTALL)
            if len(limitations) > 1:
                print('! %s: multiply limited in %s'
                      % (corpus, config))

            if license in ('ACA', 'RES') and not limitations:
                print('! %s: missing limitation in %s'
                      % (corpus, config))

            if license in ('ACA', 'RES'):
                for limitation in limitations:
                    if limitation == 'false':
                        print('! %s: incompatible non-limitation in %s'
                              % (corpus, config))
            else:
                for limitation in limitations:
                    if limitation == 'true':
                        print('! %s: incompatible limitation in %s'
                              % (corpus, config))

    if len(found_containing) == 0:
        print('! %s: not found in any config file' % corpus)

    if len(found_containing) > 1:
        print('! %s: found in more than one config file: %s'
              % (corpus, ' '.join(found_containing)))

if __name__ == '__main__':
    conn = MySQLdb.connect(host = "localhost",
                           user = DBUSER,
                           port = 3307,
                           passwd = DBPASS,
                           db = DBNAME,
                           use_unicode = True,
                           read_default_file="/var/lib/mariadb/my.cnf",
                           charset = "utf8")
    try:
        cursor = conn.cursor()
        command, args = sys.argv[1], sys.argv[2:]
        dispatch.get(command, usage_command)(cursor, command, args)
        cursor.close()
        conn.commit()
    except:
        import traceback
        traceback.print_exc(2)
        print()
        print('Try "./auth help" for usage')
